// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTbjZMXMlXTMkgXnnsVZjNk6qNH2S78X4',
    appId: '1:748681804678:web:7977dc0b18ffe8c6468a07',
    messagingSenderId: '748681804678',
    projectId: 'nachhilfeapp-d141c',
    authDomain: 'nachhilfeapp-d141c.firebaseapp.com',
    storageBucket: 'nachhilfeapp-d141c.appspot.com',
    measurementId: 'G-L36WDG7MQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKbL4oasTLy7ct087oLGzYn6i3-_T9SiA',
    appId: '1:748681804678:android:6e5d9f389a2b315a468a07',
    messagingSenderId: '748681804678',
    projectId: 'nachhilfeapp-d141c',
    storageBucket: 'nachhilfeapp-d141c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmIDM6MaqQ6OpbCytMyLR29_lD56iERj0',
    appId: '1:748681804678:ios:a3e354a1853bf1dc468a07',
    messagingSenderId: '748681804678',
    projectId: 'nachhilfeapp-d141c',
    storageBucket: 'nachhilfeapp-d141c.appspot.com',
    iosClientId: '748681804678-8bmiduneijgv0t7h13r9u056p3rsj79o.apps.googleusercontent.com',
    iosBundleId: 'com.example.nachhilfeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmIDM6MaqQ6OpbCytMyLR29_lD56iERj0',
    appId: '1:748681804678:ios:a3e354a1853bf1dc468a07',
    messagingSenderId: '748681804678',
    projectId: 'nachhilfeapp-d141c',
    storageBucket: 'nachhilfeapp-d141c.appspot.com',
    iosClientId: '748681804678-8bmiduneijgv0t7h13r9u056p3rsj79o.apps.googleusercontent.com',
    iosBundleId: 'com.example.nachhilfeApp',
  );
}
